//! The phone Share-sheet Shortcut and the Inbox folder it shares into.
//!
//! `resources/shortcuts/save-to-cancan-inbox.shortcut` is the reviewed
//! artifact: the Shortcut in Apple's pre-signing plist format, generated by
//! `scripts/shortcuts/build-save-to-cancan-inbox.py` and recorded beside its
//! digest in `resources/shortcuts/manifest.json`. This module embeds both, so
//! the artifact the app installs is the one this build was reviewed with, and
//! the module tests fail when the three drift apart.
//!
//! Two side-effect-free jobs live here:
//!
//! * [`materialize_artifact`] writes the embedded bytes where the install
//!   action signs and opens them. Nothing about the artifact depends on the
//!   Vault, the database, or the user's Inbox.
//! * [`check_inbox_destination`] proves the authorized Inbox can be written to
//!   and read back by creating a sentinel, verifying its bytes, and removing it
//!   again. A file that is already there is never touched or removed: the check
//!   fails with [`PhoneShortcutInboxCheckFailure::Occupied`] instead.
//!
//! The check's outcome is a device-local fact — the phone writes into an iCloud
//! folder, not into the Vault — so [`PhoneShortcutInboxCheck`] also carries the
//! encoding the host stores next to the Vault, and a record written for another
//! artifact version decodes to `never_checked` rather than to a stale pass.

use serde::{Deserialize, Serialize};
use std::{
    fs,
    io::{self, Write},
    path::{Path, PathBuf},
    sync::LazyLock,
};

/// The artifact's file name inside `resources/shortcuts/`.
pub(crate) const PHONE_SHORTCUT_ARTIFACT_FILE_NAME: &str = "save-to-cancan-inbox.shortcut";
/// The signed copy the install action hands to Shortcuts, beside the artifact.
pub(crate) const PHONE_SHORTCUT_SIGNED_FILE_NAME: &str = "Save to CanCan Inbox.signed.shortcut";
/// The sentinel the Inbox check creates, reads back, and removes.
pub(crate) const PHONE_SHORTCUT_CHECK_FILE_NAME: &str = "CanCan Inbox check.txt";
/// What that sentinel contains. iCloud can leave a copy visible for a moment
/// after the check removes it, so the file explains itself to whoever finds it:
/// what wrote it, that it is removed again, and that it is not evidence.
pub(crate) const PHONE_SHORTCUT_CHECK_MARKER: &str = "CanCan Inbox check. CanCan created this file to confirm your Inbox folder is reachable, and removes it again. It is not evidence.";

const PHONE_SHORTCUT_ARTIFACT: &[u8] =
    include_bytes!("../../../../resources/shortcuts/save-to-cancan-inbox.shortcut");
const PHONE_SHORTCUT_MANIFEST: &str = include_str!("../../../../resources/shortcuts/manifest.json");

const CHECK_STATUS_MAGIC: &[u8; 8] = b"CCPHONE1";
const CHECK_STATUS_LEN: usize = CHECK_STATUS_MAGIC.len() + 4 + 2;
const CHECK_STATE_NEVER_CHECKED: u8 = 0;
const CHECK_STATE_PASSED: u8 = 1;
const CHECK_STATE_FAILED: u8 = 2;
const CHECK_REASON_NONE: u8 = 0;

/// The versioned record every build reads back, so an artifact that changes
/// invalidates the Inbox check it was proven with.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct PhoneShortcutManifest {
    version: u32,
    name: String,
}

/// The parsed manifest. Its JSON is an embedded constant, so the only failure
/// mode is a build that ships an unparsable manifest, which the module tests
/// reject before it can be built.
static MANIFEST: LazyLock<PhoneShortcutManifest> = LazyLock::new(|| {
    serde_json::from_str(PHONE_SHORTCUT_MANIFEST)
        .expect("the embedded Shortcut manifest is valid JSON")
});

/// The version of the Shortcut artifact this build installs.
pub(crate) fn version() -> u32 {
    MANIFEST.version
}

/// The name Shortcuts shows when the artifact is imported.
pub(crate) fn name() -> &'static str {
    &MANIFEST.name
}

/// Writes the embedded artifact into `directory` and returns its path. The
/// bytes are the reviewed ones: a materialized copy is always a fresh write of
/// the embedded artifact, never an edited file.
pub(crate) fn materialize_artifact(directory: &Path) -> io::Result<PathBuf> {
    fs::create_dir_all(directory)?;
    let path = directory.join(PHONE_SHORTCUT_ARTIFACT_FILE_NAME);
    fs::write(&path, PHONE_SHORTCUT_ARTIFACT)?;
    Ok(path)
}

/// How the last Inbox check ended.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
#[cfg_attr(test, derive(ts_rs::TS))]
pub(crate) enum PhoneShortcutInboxCheckState {
    NeverChecked,
    Passed,
    Failed,
}

/// Why an Inbox check failed, as the stable code the renderer maps to copy and
/// the recorded check keeps for the next launch.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum PhoneShortcutInboxCheckFailure {
    /// A file with the sentinel's name is already there.
    Occupied,
    /// The sentinel could not be created or written — the usual cause is an
    /// Inbox folder the host has lost write access to.
    Write,
    /// The sentinel could not be read back byte for byte.
    ReadBack,
    /// The sentinel could not be removed again, so the Inbox now holds a file
    /// CanCan put there and failed to take back.
    Cleanup,
}

impl PhoneShortcutInboxCheckFailure {
    pub(crate) const fn code(self) -> &'static str {
        match self {
            Self::Occupied => "inbox_check_occupied",
            Self::Write => "inbox_check_write_failed",
            Self::ReadBack => "inbox_check_read_failed",
            Self::Cleanup => "inbox_check_cleanup_failed",
        }
    }

    const fn byte(self) -> u8 {
        match self {
            Self::Occupied => 1,
            Self::Write => 2,
            Self::ReadBack => 3,
            Self::Cleanup => 4,
        }
    }

    fn from_byte(byte: u8) -> Option<Self> {
        match byte {
            1 => Some(Self::Occupied),
            2 => Some(Self::Write),
            3 => Some(Self::ReadBack),
            4 => Some(Self::Cleanup),
            _ => None,
        }
    }

    fn from_code(code: &str) -> Option<Self> {
        match code {
            "inbox_check_occupied" => Some(Self::Occupied),
            "inbox_check_write_failed" => Some(Self::Write),
            "inbox_check_read_failed" => Some(Self::ReadBack),
            "inbox_check_cleanup_failed" => Some(Self::Cleanup),
            _ => None,
        }
    }
}

/// The device-local outcome of the Inbox check, as the renderer reads it and as
/// the host records it.
#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
#[cfg_attr(test, derive(ts_rs::TS))]
pub(crate) struct PhoneShortcutInboxCheck {
    pub(crate) state: PhoneShortcutInboxCheckState,
    /// The failure code, present exactly when `state` is `failed`.
    pub(crate) reason: Option<String>,
}

impl PhoneShortcutInboxCheck {
    pub(crate) const fn never_checked() -> Self {
        Self {
            state: PhoneShortcutInboxCheckState::NeverChecked,
            reason: None,
        }
    }

    pub(crate) const fn passed() -> Self {
        Self {
            state: PhoneShortcutInboxCheckState::Passed,
            reason: None,
        }
    }

    pub(crate) fn failed(failure: PhoneShortcutInboxCheckFailure) -> Self {
        Self {
            state: PhoneShortcutInboxCheckState::Failed,
            reason: Some(failure.code().to_string()),
        }
    }

    fn failure(&self) -> Option<PhoneShortcutInboxCheckFailure> {
        self.reason
            .as_deref()
            .and_then(PhoneShortcutInboxCheckFailure::from_code)
    }

    /// The record the host stores beside the Vault: magic, the artifact version
    /// the check was proven against, the state, and the failure reason.
    pub(crate) fn encode(&self) -> Vec<u8> {
        let (state, reason) = match (self.state, self.failure()) {
            (PhoneShortcutInboxCheckState::Passed, _) => (CHECK_STATE_PASSED, CHECK_REASON_NONE),
            (PhoneShortcutInboxCheckState::Failed, Some(failure)) => {
                (CHECK_STATE_FAILED, failure.byte())
            }
            // Nothing else is ever written: `failed` is the only way to build a
            // failed check, and a never-checked state is the absence of a
            // record. Encoding it anyway keeps this total.
            (
                PhoneShortcutInboxCheckState::NeverChecked | PhoneShortcutInboxCheckState::Failed,
                _,
            ) => (CHECK_STATE_NEVER_CHECKED, CHECK_REASON_NONE),
        };
        let mut bytes = Vec::with_capacity(CHECK_STATUS_LEN);
        bytes.extend_from_slice(CHECK_STATUS_MAGIC);
        bytes.extend_from_slice(&version().to_le_bytes());
        bytes.push(state);
        bytes.push(reason);
        bytes
    }

    /// Decodes a record, or returns `None` for anything this build cannot take
    /// at face value: a truncated, foreign, or corrupt record, and a record
    /// written for another artifact version. Every one of those means the
    /// destination has to be proven again.
    pub(crate) fn decode(bytes: &[u8]) -> Option<Self> {
        if bytes.len() != CHECK_STATUS_LEN
            || &bytes[..CHECK_STATUS_MAGIC.len()] != CHECK_STATUS_MAGIC
        {
            return None;
        }
        let version_offset = CHECK_STATUS_MAGIC.len();
        let recorded =
            u32::from_le_bytes(bytes[version_offset..version_offset + 4].try_into().ok()?);
        if recorded != version() {
            return None;
        }
        let state = bytes[version_offset + 4];
        let reason = bytes[version_offset + 5];
        match (state, reason) {
            (CHECK_STATE_PASSED, CHECK_REASON_NONE) => Some(Self::passed()),
            (CHECK_STATE_FAILED, reason) => Some(Self::failed(
                PhoneShortcutInboxCheckFailure::from_byte(reason)?,
            )),
            (CHECK_STATE_NEVER_CHECKED, CHECK_REASON_NONE) => Some(Self::never_checked()),
            _ => None,
        }
    }
}

/// Creates the sentinel in `inbox`, verifies its bytes, and removes it again.
///
/// The sentinel is the whole point of the test action: a bookmark that resolves
/// and a directory that lists are not the same as a folder the host can write
/// to. Failure is reported as the reason the check could not complete; the
/// sentinel is removed on every path that created it.
pub(crate) fn check_inbox_destination(inbox: &Path) -> Result<(), PhoneShortcutInboxCheckFailure> {
    let sentinel = inbox.join(PHONE_SHORTCUT_CHECK_FILE_NAME);
    let mut file = match fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&sentinel)
    {
        Ok(file) => file,
        Err(error) if error.kind() == io::ErrorKind::AlreadyExists => {
            return Err(PhoneShortcutInboxCheckFailure::Occupied);
        }
        Err(_) => return Err(PhoneShortcutInboxCheckFailure::Write),
    };
    let written = file
        .write_all(PHONE_SHORTCUT_CHECK_MARKER.as_bytes())
        .and_then(|()| file.sync_all())
        .map_err(|_| PhoneShortcutInboxCheckFailure::Write);
    drop(file);
    let verified = written.and_then(|()| verify_sentinel(&sentinel));
    remove_sentinel(&sentinel, verified)
}

/// Reads the sentinel back and requires the exact bytes it was written with: a
/// folder whose writes do not survive is not a destination CanCan can read a
/// capture from either.
fn verify_sentinel(sentinel: &Path) -> Result<(), PhoneShortcutInboxCheckFailure> {
    let read_back = fs::read(sentinel).map_err(|_| PhoneShortcutInboxCheckFailure::ReadBack)?;
    if read_back == PHONE_SHORTCUT_CHECK_MARKER.as_bytes() {
        Ok(())
    } else {
        Err(PhoneShortcutInboxCheckFailure::ReadBack)
    }
}

/// Removes the sentinel this check created. A sentinel that cannot be removed
/// outranks whatever went wrong before it: a file CanCan left in the user's
/// Inbox is what has to be dealt with.
fn remove_sentinel(
    sentinel: &Path,
    outcome: Result<(), PhoneShortcutInboxCheckFailure>,
) -> Result<(), PhoneShortcutInboxCheckFailure> {
    match fs::remove_file(sentinel) {
        Ok(()) => outcome,
        Err(_) => Err(PhoneShortcutInboxCheckFailure::Cleanup),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::local_inbox::{sha256_hex, supported_source};

    /// The manifest exactly as `scripts/shortcuts/build-save-to-cancan-inbox.py`
    /// writes it. The host reads only the version and name; the rest is checked
    /// here so a regenerated artifact cannot ship with a stale record.
    #[derive(Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct CommittedManifest {
        artifact: String,
        destination_path: String,
        name: String,
        receipt_text: String,
        sha256: String,
        version: u32,
    }

    fn committed_manifest() -> CommittedManifest {
        serde_json::from_str(PHONE_SHORTCUT_MANIFEST).expect("committed manifest is valid JSON")
    }

    #[test]
    fn embedded_artifact_is_the_reviewed_one() {
        let manifest = committed_manifest();
        assert_eq!(manifest.artifact, PHONE_SHORTCUT_ARTIFACT_FILE_NAME);
        assert_eq!(manifest.sha256, sha256_hex(PHONE_SHORTCUT_ARTIFACT));
        assert_eq!(manifest.version, version());
        assert_eq!(manifest.name, name());
    }

    #[test]
    fn artifact_lands_where_the_setup_instructions_say_it_does() {
        let manifest = committed_manifest();
        assert_eq!(manifest.destination_path, "/Cancan/Inbox/");
        assert!(manifest.receipt_text.contains("CanCan"));
    }

    #[test]
    fn the_check_sentinel_is_never_importable_evidence() {
        // A sentinel survives only when its cleanup failed. It is a text file,
        // which is outside the capture surface, so a later scan cannot turn it
        // into a source document.
        assert!(!supported_source(Path::new(PHONE_SHORTCUT_CHECK_FILE_NAME)));
    }

    #[test]
    fn inbox_check_records_round_trip() {
        for check in [
            PhoneShortcutInboxCheck::never_checked(),
            PhoneShortcutInboxCheck::passed(),
            PhoneShortcutInboxCheck::failed(PhoneShortcutInboxCheckFailure::Occupied),
            PhoneShortcutInboxCheck::failed(PhoneShortcutInboxCheckFailure::Write),
            PhoneShortcutInboxCheck::failed(PhoneShortcutInboxCheckFailure::ReadBack),
            PhoneShortcutInboxCheck::failed(PhoneShortcutInboxCheckFailure::Cleanup),
        ] {
            assert_eq!(
                PhoneShortcutInboxCheck::decode(&check.encode()),
                Some(check)
            );
        }
        assert_eq!(
            PhoneShortcutInboxCheck::failed(PhoneShortcutInboxCheckFailure::Write).reason,
            Some("inbox_check_write_failed".to_string())
        );
    }

    #[test]
    fn a_record_this_build_cannot_take_at_face_value_is_never_checked() {
        let version_offset = CHECK_STATUS_MAGIC.len();
        let passed = PhoneShortcutInboxCheck::passed();
        assert_eq!(passed.state, PhoneShortcutInboxCheckState::Passed);

        let mut other_version = passed.encode();
        other_version[version_offset] = other_version[version_offset].wrapping_add(1);
        assert_eq!(PhoneShortcutInboxCheck::decode(&other_version), None);

        let mut unknown_state = passed.encode();
        unknown_state[version_offset + 4] = 9;
        assert_eq!(PhoneShortcutInboxCheck::decode(&unknown_state), None);

        let mut failed_without_reason = passed.encode();
        failed_without_reason[version_offset + 4] = CHECK_STATE_FAILED;
        assert_eq!(
            PhoneShortcutInboxCheck::decode(&failed_without_reason),
            None
        );

        let mut foreign_magic = passed.encode();
        foreign_magic[..CHECK_STATUS_MAGIC.len()].copy_from_slice(b"CCOTHER1");
        assert_eq!(PhoneShortcutInboxCheck::decode(&foreign_magic), None);

        let mut truncated = passed.encode();
        truncated.pop();
        assert_eq!(PhoneShortcutInboxCheck::decode(&truncated), None);
        assert_eq!(PhoneShortcutInboxCheck::decode(b""), None);

        let mut extended = passed.encode();
        extended.push(CHECK_REASON_NONE);
        assert_eq!(PhoneShortcutInboxCheck::decode(&extended), None);
    }

    #[test]
    fn inbox_check_creates_verifies_and_removes_its_sentinel() {
        let inbox = tempfile::tempdir().expect("temporary Inbox");
        assert_eq!(check_inbox_destination(inbox.path()), Ok(()));
        assert_eq!(
            fs::read_dir(inbox.path()).expect("read Inbox").count(),
            0,
            "the check leaves the Inbox as it found it"
        );
    }

    #[test]
    fn inbox_check_keeps_a_file_that_is_already_there() {
        let inbox = tempfile::tempdir().expect("temporary Inbox");
        let sentinel = inbox.path().join(PHONE_SHORTCUT_CHECK_FILE_NAME);
        fs::write(&sentinel, b"someone else's file").expect("write existing file");
        assert_eq!(
            check_inbox_destination(inbox.path()),
            Err(PhoneShortcutInboxCheckFailure::Occupied)
        );
        assert_eq!(
            fs::read(&sentinel).expect("read existing file"),
            b"someone else's file"
        );
    }

    #[test]
    fn inbox_check_reports_an_inbox_that_is_not_there() {
        let parent = tempfile::tempdir().expect("temporary app data");
        assert_eq!(
            check_inbox_destination(&parent.path().join("Inbox")),
            Err(PhoneShortcutInboxCheckFailure::Write)
        );
    }

    #[cfg(unix)]
    #[test]
    fn inbox_check_reports_an_inbox_it_cannot_write_to() {
        use std::os::unix::fs::PermissionsExt;

        let parent = tempfile::tempdir().expect("temporary app data");
        let inbox = parent.path().join("Inbox");
        fs::create_dir(&inbox).expect("create Inbox");
        fs::set_permissions(&inbox, fs::Permissions::from_mode(0o500)).expect("read-only Inbox");
        let outcome = check_inbox_destination(&inbox);
        fs::set_permissions(&inbox, fs::Permissions::from_mode(0o700)).expect("writable Inbox");
        assert_eq!(outcome, Err(PhoneShortcutInboxCheckFailure::Write));
        assert_eq!(
            fs::read_dir(&inbox).expect("read Inbox").count(),
            0,
            "an Inbox the check could not write to is left as it was"
        );
    }

    #[test]
    fn sentinel_verification_requires_the_exact_bytes() {
        let parent = tempfile::tempdir().expect("temporary app data");
        let sentinel = parent.path().join("sentinel");
        fs::write(&sentinel, PHONE_SHORTCUT_CHECK_MARKER.as_bytes()).expect("write marker");
        assert_eq!(verify_sentinel(&sentinel), Ok(()));
        fs::write(&sentinel, b"changed after the write").expect("change bytes");
        assert_eq!(
            verify_sentinel(&sentinel),
            Err(PhoneShortcutInboxCheckFailure::ReadBack)
        );
        assert_eq!(
            verify_sentinel(&parent.path().join("absent")),
            Err(PhoneShortcutInboxCheckFailure::ReadBack)
        );
    }

    #[test]
    fn a_cleanup_failure_outranks_the_failure_before_it() {
        let parent = tempfile::tempdir().expect("temporary app data");
        // A non-empty directory is the shape of a sentinel `remove_file`
        // refuses, which is exactly the case the cleanup code exists for.
        let sentinel = parent.path().join("sentinel");
        fs::create_dir(&sentinel).expect("create directory");
        fs::write(sentinel.join("child"), b"child").expect("write child");
        assert_eq!(
            remove_sentinel(&sentinel, Err(PhoneShortcutInboxCheckFailure::Write)),
            Err(PhoneShortcutInboxCheckFailure::Cleanup)
        );
        assert_eq!(
            remove_sentinel(&sentinel, Ok(())),
            Err(PhoneShortcutInboxCheckFailure::Cleanup)
        );
    }

    #[test]
    fn materializing_writes_the_embedded_artifact_beside_the_vault() {
        let parent = tempfile::tempdir().expect("temporary app data");
        let directory = parent.path().join("phone-shortcut");
        let path = materialize_artifact(&directory).expect("materialize artifact");
        assert_eq!(path, directory.join(PHONE_SHORTCUT_ARTIFACT_FILE_NAME));
        let materialized = fs::read(&path).expect("read artifact");
        assert_eq!(materialized, PHONE_SHORTCUT_ARTIFACT);
        assert_eq!(sha256_hex(&materialized), committed_manifest().sha256);
        // A second install replaces the copy instead of failing on it.
        assert_eq!(
            materialize_artifact(&directory).expect("replace artifact"),
            path
        );
        assert_eq!(fs::read(&path).expect("read artifact"), materialized);
    }
}
