packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - "@typescript/*"
  - "@types/node@24.13.3"
  - typescript@7.0.2
  - vite@8.1.4

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 10080
